### ISSUE TITLE
Cache dumps

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#7]
Rather than downloading everytime for instance `frwikivoyage/latest/frwikivoyage-latest-pages-articles.xml.bz2`, we should:

1. Open the versions list page https://dumps.wikimedia.org/frwikivoyage/
2. Select the latest version
3. Download it as `dump_fr_20151102.xml.bz2` rather than just `dump.xml.bz2`
4. Reuse the dump next time if no new version is available.
5. Old version should be deleted when newer version is downloaded

This is more sustainable than implementing caching mechanisms outside of the tool. This ensures that other people who use the tool do not overload the poor donation-funded Wikimedia servers.

**Comment by baturin** [comment]
1. I've added dumps caching for -input-latest option. Cached dumps are stored in "dumps-cache" directory.
2. For daily update that feature already works since it was initially developed. All dumps are downloaded to http://wvpoi.batalex.ru/wikivoyage-dumps/.
3. I'm not sure about item number 5 in the list: personally I would like to have all dumps stored, even the previous old ones. Sometimes it is useful to compare results provided by different dump versions.

**Comment by nicolas-raoul** [comment]
Great! :-)
